
[General]
	#Allows players to receive extra hearts based on their doriki
	#Default: true
	"Extra Hearts" = true
	#Allows mobs to reward doriki, bounty or items
	#Default: true
	"Mob Rewards" = true
	#Guarantees a minimum of 1 doriki per kill
	# If used together with a Haki Exp Multiplier with a multiplier less than <1.0 it will convert it to chances
	#Default: false
	"Minimum Doriki per Kill" = true
	#Destroys the spawner after all its spawns are killed
	#Default: true
	"Destroy Spawner" = true
	#Allows big explosions to destroy water 
	#Default: false
	"Destroy Water" = false
	#Randomizes the player's race at spawn (making the player unable to choose a race themselves) 
	#Default: false
	"Race Randomizer" = false
	#Allows the players to pickup items while the combat bar is active 
	#Default: true
	"Combat Bar Pickup" = true
	#Allows vanilla and other modded NPCs to use Busoshoku Haki, has no visual effect on their model however and its purely mechanical 
	#Default: true
	"Native Haki" = true
	#Allows non-OP users to use /removedf command ON THEMSELVES! 
	#Default: false
	"Public /removedf" = false
	#Normally despawns traders and trainers even if they're nametagged 
	#Default: false
	"Despawn NPCs with Nametags" = false
	#Forces new players to select their race, faction and fighting style upon joining the world
	#Default: false
	"Force Selection" = false
	#List with item ids that will not get the durability protection of Imbuing Haki
	"Banned Items from Imbuing" = ["mineminenomi:bubbly_coral"]
	#Sets a new limit for maximum doriki a player may obtain 
	#Default: 10000
	#Range: 0 ~ 100000
	"Doriki Limit" = 10000
	#Sets a new limit for maximum haki exp a player may obtain 
	#Default: 100
	#Range: 0 ~ 300
	"Haki Exp Limit" = 100
	#Defines at what doriki intervals an extra +1 HP is gained
	#Default: 40
	#Range: 40 ~ 100
	"Health Gain Frequency" = 40
	#Multiplies any doriki gained from non-player kills by this amount (commands not included)
	#Default: 1
	#Range: 0.0 ~ 10.0
	"Doriki Reward Multiplier" = 1.0
	#Multiplies any belly gained from non-player kills by this amount (commands not included)
	#Default: 1
	#Range: 0.0 ~ 10.0
	"Belly Reward Multiplier" = 1.0
	#Multiplies any bounty gained from non-player kills by this amount (commands not included)
	#Default: 1
	#Range: 0.0 ~ 10.0
	"Bounty Reward Multiplier" = 1.0
	#Multiplies any haki gained from non-player kills by this amount (commands not included)
	#Default: 1
	#Range: 0.0 ~ 10.0
	"Haki Exp Multiplier" = 1.0
	#Multiplies any loyalty gained by this amount (commands not included)
	#Default: 1
	#Range: 0.0 ~ 10.0
	"Loyalty Multiplier" = 1.0
	#Defines which logic to apply after a player's death 
	# NONE - nothing is kept 
	# AUTO - only the faction/race/fighting style stats are kept 
	# FULL - everything is kept 
	# CUSTOM - will use the 'Stats to Keep' section to determine which stats to keep
	#Default: AUTO
	#Allowed Values: NONE, AUTO, FULL, CUSTOM
	"Keep Stats after Death" = "AUTO"

	#Please note that these settings only work if the "Keep stats after Death" option is set to CUSTOM!
	[General."Stats to Keep"]
		"Keep Race" = true
		"Keep Faction" = true
		"Keep Fighting Style" = true
		"Keep Devil Fruit" = true
		#Percentage of doriki to keep after death
		#Default: 33
		#Range: 0 ~ 100
		"Percentage of Doriki kept after death" = 33
		#Percentage of bounty to keep after death
		#Default: 33
		#Range: 0 ~ 100
		"Percentage of Bounty kept after death" = 33
		#Percentage of belly to keep after death
		#Default: 33
		#Range: 0 ~ 100
		"Percentage of Belly kept after death" = 33
		#Percentage of haki exp to keep after death
		#Default: 33
		#Range: 0 ~ 100
		"Percentage of Haki Exp kept after death" = 33
		#Percentage of faction loyalty to keep after death
		#Default: 50
		#Range: 0 ~ 100
		"Percentage of Loyalty kept after death" = 50

	[General."Quests & Trials"]
		#Allows quests to be accepted / completed
		#Default: true
		"Enable Trials" = true
		#Allows quests to reward players with abilities, otherwise all abilities will be unlocked from the beginning
		#Default: true
		"Enable Fighting Style Progression" = true

["Devil Fruits / Abilities"]
	#Allows abilities to break or replace blocks; if turned OFF it will make some abilities completly useless
	#Default: true
	"Ability Griefing" = true
	#Runs a check for all abilities on a player to remove dupes or suspicious abilities when the player joins the world
	#Default: true
	"Ability Fraud Checks" = true
	#Number of ability bars;
	#Default: 2
	#Range: 1 ~ 10
	"Ability Bars" = 2
	#Allows Yami Yami no Mi users to eat an additional fruit
	#Default: true
	"Yami Power" = true
	#Makes getting out of water much harder as it's supposed to be
	#Default: false
	"Devil Fruit Extended Weakness Checks" = false
	#Enables the shared cooldown between similar abilities
	#Default: true
	"Shared Cooldowns" = true
	#Remove the Y level restriction for flying moves
	#Default: false
	"Remove Y Restriction" = false
	#Will randomize all visual aspects of a devil fruit, making them impossible to identify
	#Default: false
	"Randomized Fruits" = false
	#Allows Devil Fruits to drop from leaves if higher than 0
	#Default: 0
	#Range: 0.0 ~ 100.0
	"Chance for Devil Fruits to drop from leaves" = 0.0
	#Enables logia's invulnerability
	"Logia Invulnerability" = true
	#Allows logia users to have different effects when punched
	#Default: false
	"Logia Return Effect" = false
	#How logias get affected by projectiles; 
	# NONE - No projectile can damage logias 
	# HAKI - Physical projectiles with buso cause damage 
	# EXTENDED - HAKI + any attack considered special deals damage to logias 
	#Default: EXTENDED
	#Allowed Values: NONE, HAKI, EXTENDED
	"Logia Projectiles Invulnerability" = "EXTENDED"
	#Invulnerability to avoid attacks
	#Default: true
	"Ability Invulnerability" = true
	#Makes the fire and lava damage source to reduce fire resistance; only applies to move attacks from fruits 
	#Default: true
	"Special Source Events" = true
	#Used to determine the logic for when a continuous ability is used while another continuous ability is being used;
	# true - Currently used ability is stopped and the newly used ability starts its process
	# false - The current ability is NOT stopped and the used ability has no effect
	#Default: true
	"Stop Continuous Abilities" = true
	#Will send a chat message to nearby players with the used ability's name
	#Default: false
	"Anime Scream" = false
	#List with ability names that are banned from the mod entirely
	#Names should be written using the modid:name model similar to the below examples, if no modid is provided 'mineminenomi' will be applied by default.
	"Banned Abilities" = ["mineminenomi:example1"]

	#These options only work when "One Fruit per World" option is set to EXTENDED!
	["Devil Fruits / Abilities"."One Fruit Per World"]
		#Restricts the Devil Fruit spawns to only 1 of each type per world; 
		# NONE - No logic is applied, an infinite number of each fruit can exist 
		# SIMPLE - No more than one fruit type can be acquired via natural means (chests, leaves, fruit reincarnations etc) 
		# EXTENDED - Extra rules are applied on top of the SIMPLE set that blocks any means (or as many as possible) of storing/hoarding fruits 
		#Default: NONE
		#Allowed Values: NONE, SIMPLE, EXTENDED
		"One Fruit per World" = "NONE"
		#If the player already has a devil fruit then they will be unable to pickup any other fruit;
		#Default: false
		"Unable to pickup Devil Fruit as a fruit user" = false
		#Sets the limit for how many fruits a player can hold in their inventory;
		#Default: 3
		#Range: 1 ~ 10
		"Inventory Fruit Limit" = 3
		#Defines how many days a player has to be offline before their Devil Fruits are removed
		#A value of 0 means the setting is disabled and fruits will not be removed for inactivity!;
		#Default: 6
		#Range: 0 ~ 30
		"Days for Inactivity" = 6

	["Devil Fruits / Abilities"."Devil Fruits Reincarnation"]
		#Sets the % chance for a Devil Fruit to get reincarnated from a dropped apple
		#Default: 15
		#Range: 0 ~ 100
		"Dropped Apple Reincarnation Chance" = 15
		#Sets the % chance for a Devil Fruit to get reincarnated from an apple inside an entity's inventory
		#Default: 1
		#Range: 0 ~ 100
		"Entity's Inventory Apple Reincarnation Chance" = 15
		#Sets the % chance for a Devil Fruit to get reincarnated from an apple inside of a nearby chest
		#Default: 1
		#Range: 0 ~ 100
		"Chest Blocks Apple Reincarnation Chance" = 15

	["Devil Fruits / Abilities"."Ability Protection"]
		#List with ability names that can be used inside ability protection zones
		#Names should be written using the modid:name model similar to the below examples, if no modid is provided 'mineminenomi' will be applied by default.
		"Protection Whitelist" = ["mineminenomi:example1"]
		#Time (in ticks) before a newly replaced block will get restored inside ability protection areas
		#Default 400
		#Range: 0 ~ 72000
		"Global Protection Restoration Grace" = 400
		#If players are closer than 10 blocks from an area marked for restoration this area will be paused as to not trap or otherwise suffocate the player
		#Default true
		"Stop Restoration Near Players" = true

	["Devil Fruits / Abilities".Haki]
		#Responsible for how player unlock Haoshoku Haki; 
		# NONE - Haoshoku Haki cannot be unlocked naturally 
		# RANDOM - Only a few chosen ones receive it when they spawn 
		# EXPERIENCE - Will unlock based on the total amount of Haki experience a player has
		# COMBINED - Combiens the logic of RANDOM and EXPERIENCE
		# TRUE_RANDOM - Each world / server has its own pool of randomly chosen Haoshoku Haki users
		#Default: COMBINED
		#Allowed Values: NONE, RANDOM, EXPERIENCE, COMBINED, TRUE_RANDOM
		"Haoshoku Haki Unlock Logic" = "COMBINED"
		#Responsible for how a player's Haoshoku Haki outline will be colored; 
		# STANDARD - Standard red outline 
		# CUSTOM - Allows the player to customize it using their own client config 
		# RANDOM - Assignes a random color for each player based on their account's UUID
		#Default: STANDARD
		#Allowed Values: STANDARD, CUSTOM, RANDOM
		"Haoshoku Haki Coloring Logic" = "STANDARD"

["World Features"]
	#Sets the % chance for a training structure to spawn
	#Default: 50
	#Range: 0 ~ 100
	"Training Structure Spawn Chance" = 25
	#Sets the % chance for a Ghost Ship to spawn, the % is calculated per chunk (16x16)
	#Default: 50
	#Range: 0 ~ 100
	"Ghost Ships Spawn Chance" = 25
	#Sets the % chance for a Sky Island to spawn, the % is calculated per chunk (16x16)
	#Default: 50
	#Range: 0 ~ 100
	"Sky Islands Spawn Chance" = 25
	#Sets the % chance for a Small Ship to spawn, the % is calculated per chunk (16x16)
	#Default: 50
	#Range: 0 ~ 100
	"Small Ships Spawn Chance" = 25
	#Sets the % chance for a Medium Ship to spawn, the % is calculated per chunk (16x16)
	#Default: 50
	#Range: 0 ~ 100
	"Medium Ships Spawn Chance" = 25
	#Sets the % chance for a Large Ship to spawn, the % is calculated per chunk (16x16)
	#Default: 50
	#Range: 0 ~ 100
	"Large Ships Spawn Chance" = 25
	#Sets the % chance for a Camp to spawn, the % is calculated per chunk (16x16)
	#Default: 10
	#Range: 0 ~ 100
	"Camps Spawn Chance" = 10
	#Sets the % chance for a Small Base to spawn, the % is calculated per chunk (16x16)
	#Default: 50
	#Range: 0 ~ 100
	"Small Bases Spawn Chance" = 25
	#Sets the % chance for a Large Base to spawn, the % is calculated per chunk (16x16)
	#Default: 50
	#Range: 0 ~ 100
	"Large Bases Spawn Chance" = 25
	#Sets the % chance for a Watch Tower to spawn, the % is calculated per chunk (16x16)
	#Default: 50
	#Range: 0 ~ 100
	"Watch Towers Spawn Chance" = 25
	#Sets the % chance for a Poneglyph to spawn, the % is calculated per chunk (16x16)
	#Default: 10
	#Range: 0 ~ 100
	"Poneglyphs Spawn Chance" = 10
	#Kairoseki count per chunk
	#Default: 2
	#Range: 1 ~ 20
	"Kairoseki Count" = 2

[Challenges]
	#Enabled the challenges menu and activation by players
	#Default: true
	"Enable Challenges" = true
	#Enabled retaking of already completed challenges
	#Default: false
	"Retake Challenges" = true

["World Events"]
	#Sets the % chance for a training structure to spawn
	#Default: 50
	"World NPCs Spawns" = true

	["World Events".Traders]
		#Determines the time (in minutes) between two spawn attempts
		#Default: 2 (minutes)
		#Range: 0 ~ 30
		"Time Between Trader Spawns" = 2
		#Determines the % chance for a trader to spawn
		#Default: 1
		#Range: 0 ~ 100
		"Chance for Trader Spawns" = 1

	["World Events".Trainers]
		#Determines the time (in minutes) between two spawn attempts
		#Default: 2 (minutes)
		#Range: 0 ~ 30
		"Time Between Trainer Spawns" = 2
		#Determines the % chance for a trainer to spawn
		#Default: 15
		#Range: 0 ~ 100
		"Chance for Trainer Spawns" = 15

	["World Events".Ambushes]
		#Determines the time (in minutes) between two spawn attempts
		#Default: 15 (minutes)
		#Range: 0 ~ 30
		"Time Between Ambush Spawns" = 15
		#Determines the % chance for a trainer to spawn
		#Default: 15
		#Range: 0 ~ 100
		"Chance for Ambush Spawns" = 15

[Factions]
	#Disabled the friendly damage between crewmates
	#Default: true
	"Disable Friendly Damage" = true

	[Factions.Bounty]
		#Time (in minutes) it takes for another package to drop
		#0 means no package will spawn
		#Default: 15 (minutes)
		#Range: 0 ~ 60
		"Time Between Package Drops" = 15

		[Factions.Bounty.Crews]
			#Bounty Requirement for creating a crew; 0 means no requirement
			#Default: 0
			#Range: 0 ~ 100000
			"Bounty Requirement" = 0
			#Sends a message to all players when a new crew gets formed
			#Default: false
			"World Message on Crew creations" = false

		[Factions.Bounty.System]
			#Merges all the commands added by this mod under a generic /mmnm command, used for compatibility reasons in case some other mod adds similarly named commands
			#Default: false
			"Master Command" = false

